#@ def blog_generation():
- name: blog-generation
  image: elasticdog/tiddlywiki
  args:
    - "/tiddlywiki"
    - --build-tiddler
    - "$:/litapp/blog/build-commands"
  volumeMounts:
  - name: volv
    mountPath: /tiddlywiki
- name: sync-folders
  image: alpine
  args:
    - sh
    - -c
    - |
      rm -rv /blog/*
      cp -rv /tiddlywiki/output/static/* /blog
  volumeMounts:
  - name: volv
    mountPath: /tiddlywiki
  - name: blog-data
    mountPath: /blog
#@ end

#@ def volumes():
- name: volv
  persistentVolumeClaim:
    claimName: mywiki-pvc
- name: blog-data
  persistentVolumeClaim:
    claimName: blog-pvc
- name: config
  configMap:
    defaultMode: 420
    name: caddy
    items:
    - key: "Caddyfile"
      path: "Caddyfile"
#@ end

---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: {}
  name: blog
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog
  template:
    metadata:
      labels:
        app: blog
    spec:
      containers:
      - image: caddy
        name: blog
        ports:
          - containerPort: 80
            name: http-blog
        volumeMounts:
        - name: blog-data
          mountPath: /usr/share/caddy
        - name: config
          mountPath: /etc/caddy/Caddyfile
          subPath: Caddyfile
      initContainers: #@ blog_generation()
      volumes: #@ volumes()

---
apiVersion: v1
kind: Service
metadata:
  annotations: {}
  name: blog
  namespace: default
spec:
  ports:
    - name: http-blog
      port: 8090
      targetPort: http-blog
  selector:
    app: blog

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: blog-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 10Gi

---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: update-blog
spec:
  schedule: "*/23 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers: #@ blog_generation()
          restartPolicy: Never
          volumes: #@ volumes()
      backoffLimit: 4
      ttlSecondsAfterFinished: #@ 24*60*60
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: caddy
data:
  Caddyfile: |
    :80 {
      # Set this path to your site's directory.
      root * /usr/share/caddy

      # Enable the static file server.
      file_server

      log {
        output stdout
      }
    }
