#@ load("@ytt:data", "data")

---
apiVersion: kbld.k14s.io/v1alpha1
kind: Sources
sources:
- image: tiddly_wiki_bot
  path: .
  pack:
    build:
      builder: rg.nl-ams.scw.cloud/carlo-colombo/elixir-builder
      rawOptions:
        - -e
        - RELEASE=tiddly_wiki_bot

---
apiVersion: kbld.k14s.io/v1alpha1
kind: Sources
sources:
- image: dashboard
  path: .
  pack:
    build:
      builder: rg.nl-ams.scw.cloud/carlo-colombo/elixir-builder
      rawOptions:
        - -e
        - #@ 'SECRET_KEY_BASE='+ data.values.release.secret_key_base
        - -e
        - RELEASE=dashboard

---
apiVersion: kbld.k14s.io/v1alpha1
kind: Sources
sources:
- image: feed2wiki
  path: .
  pack:
    build:
      builder: rg.nl-ams.scw.cloud/carlo-colombo/elixir-builder
      rawOptions:
        - -e
        - RELEASE=feed2wiki

---
apiVersion: kbld.k14s.io/v1alpha1
kind: Sources
sources:
- image: extract-info
  path: extract-info
  pack:
    build:
      builder: paketobuildpacks/builder:base

#! Specifies where to push app1 image
---
apiVersion: kbld.k14s.io/v1alpha1
kind: ImageDestinations
destinations:
- image: tiddly_wiki_bot
  newImage: rg.nl-ams.scw.cloud/carlo-colombo/tiddly_wiki_bot

---
apiVersion: kbld.k14s.io/v1alpha1
kind: ImageDestinations
destinations:
- image: dashboard
  newImage: rg.nl-ams.scw.cloud/carlo-colombo/dashboard

---
apiVersion: kbld.k14s.io/v1alpha1
kind: ImageDestinations
destinations:
- image: feed2wiki
  newImage: rg.nl-ams.scw.cloud/carlo-colombo/feed2wiki
#! Specifies where to push app1 image
---
apiVersion: kbld.k14s.io/v1alpha1
kind: ImageDestinations
destinations:
- image: extract-info
  newImage: rg.nl-ams.scw.cloud/carlo-colombo/extract-info
