#@ load("@ytt:data", "data")
#@ load("functions.star", "get_password")

---
apiVersion: kbld.k14s.io/v1alpha1
kind: Sources
sources:
- image: pixelfed2wiki
  path: apps/pixelfed2wiki/cmd/pixelfed2wiki
  ko:
    build: {}
- image: pixelfed-bs-bridge
  path: apps/pixelfed2wiki/cmd/pixelfed-bs-bridge
  ko:
    build: {}
---
apiVersion: kbld.k14s.io/v1alpha1
kind: ImageDestinations
destinations:
- image: pixelfed2wiki
  newImage: rg.nl-ams.scw.cloud/carlo-colombo/pixelfed2wiki
- image: pixelfed-bs-bridge
  newImage: rg.nl-ams.scw.cloud/carlo-colombo/pixelfed-bs-bridge

---

apiVersion: batch/v1
kind: CronJob
metadata:
  name: pixelfed-importer
spec:
  schedule: "42 */2 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: pixelfed2wiki
            image: pixelfed2wiki
            args:
              - https://pixelfed.social/users/lit.pictures.atom
              - http://mywiki:8080
            env:
              - name: WIKI_USERNAME
                value: bot
              - name: WIKI_PASSWORD
                value: #@ get_password(data.values.wiki.users, 'bot')
              - name: ACCESS_KEYID
                valueFrom:
                  secretKeyRef:
                    name: litapp-blog-images-creds
                    key: ACCESS_KEYID
              - name: SECRET_KEY
                valueFrom:
                  secretKeyRef:
                    name: litapp-blog-images-creds
                    key: SECRET_KEY
              - name: UPLOAD_BUCKET
                value: litapp-blog-images
          restartPolicy: Never
      backoffLimit: 4

---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: pixelfed-bs-bridge
spec:
  schedule: "*/5 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 2
      template:
        spec:
          restartPolicy: Never
          containers:
          - name: pixelfed-bs-bridge
            image: pixelfed-bs-bridge
            env:
            - name: PIXELFED_FEED_URL
              value: https://pixelfed.social/users/lit.pictures.atom
            - name: BRIDGE_AFTER
              value: "2026-09-12T18:00:00+02:00"
            - name: BLUESKY_HANDLE
              valueFrom:
                secretKeyRef:
                  name: pixelfed-bs-bridge
                  key: BLUESKY_HANDLE
            - name: BLUESKY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pixelfed-bs-bridge
                  key: BLUESKY_PASSWORD

