#@ load("@ytt:data", "data")
#@ load("@ytt:base64", "base64")
#@ load("functions.star", "csv")


apiVersion: v1
data:
  creds.csv: #@ base64.encode(csv(data.values.wiki.users))
kind: Secret
metadata:
  name: wiki-users

---
apiVersion: v1
kind: Secret
metadata:
  name: pixelfed-bs-bridge
stringData:
  BLUESKY_HANDLE: #@ data.values.bluesky.handle
  BLUESKY_PASSWORD: #@ data.values.bluesky.password
