#@ load("@ytt:data", "data")
#@ load("@ytt:base64", "base64")
#@ load("functions.star", "csv")


apiVersion: v1
data:
  creds.csv: #@ base64.encode(csv(data.values.wiki.users))
kind: Secret
metadata:
  name: wiki-users
