#@ load("@ytt:data", "data")
#@ load("functions.star", "get_password")

---
apiVersion: v1
kind: Service
metadata:
  annotations: {}
  name: mywiki
  namespace: default
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: mywiki

---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: {}
  name: mywiki
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mywiki
  template:
    metadata:
      labels:
        app: mywiki
    spec:
      containers:
        - image: tiddlywiki
          name: mywiki
          volumeMounts:
          - name: volv
            mountPath: /tiddlywiki
          - name: users
            mountPath: /tiddlywiki/creds
          args:
            - /tiddlywiki
            - --listen
            - host=0.0.0.0
            - "username=$(USERNAME)"
            - "password=$(PASSWORD)"
            - credentials=creds/creds.csv
            - "writers=$(USERS)"
            - "readers=$(USERS)"
            - --verbose
          env:
            - name: USERNAME
              value: admin
            - name: PASSWORD
              value: #@ get_password(data.values.wiki.users, 'admin')
            - name: USERS
              value: #@ ','.join([x.username for x in data.values.wiki.users])
      volumes:
        - name: volv
          persistentVolumeClaim:
            claimName: mywiki-pvc
        - name: users
          secret:
            secretName: wiki-users
      imagePullSecrets:
        - name: regcred

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mywiki-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 10Gi
---
apiVersion: kbld.k14s.io/v1alpha1
kind: Sources
sources:
- image: tiddlywiki
  path: apps
  docker:
    build:
      pull: true
      file: Tiddlywiki.Dockerfile
      rawOptions:
        - "--build-arg"
        - "TIDDLYWIKI_VERSION=5.2.5"
---
apiVersion: kbld.k14s.io/v1alpha1
kind: ImageDestinations
destinations:
- image: tiddlywiki
  newImage: rg.nl-ams.scw.cloud/carlo-colombo/tiddlywiki
